# Generated by Django 4.1.3 on 2022-12-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=280),
        ),
    ]
