# Generated by Django 4.1.3 on 2022-11-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="desc",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
